version: '3.8'
services:
  jenkins:
    restart: always
    build:
      context: ""
      args:
        DOCKER_GID: ${DOCKER_GID}
    container_name: jenkins
    environment:
      TZ: "Asia/Seoul"
      JAVA_OPTS: "-Dhudson.model.DownloadService.noSignatureCheck=true"
      DOCKER_GID: ${DOCKER_GID}
    ports:
      - "9090:8080"
    volumes:
      - "./volume:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
